version: '3'

services:
  mysqlsrv:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2019!"
      MYSQL_DATABASE: "rest_with_spring_boot"
    ports:
      - "3306:3306"
    volumes:
      - /home/gdarlan/Documentos/cursos/rest-with-spring-boot-and-kotlin/volumes:/var/lib/mysql
    networks:
      - mysql-network

  adminer:
    image: adminer
    ports:
      - '8081:8080'
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
